nombre=input("ingresa tu nombre: ")
apellido=input("ingresa tu apellido: ")
num=input("ingresa tu numero de alumno: ")
comision=input("ingresa la comision a la que deseas suscribirte: ")
print("La solicitud de inscripción a la comisión solicitada por el alumno " + nombre, "está siendo procesada")
